name: Tests against Java Driver Verions

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  install:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver_version: [ 4.10.0, 4.11.0, 4.11.1, 4.11.2, 4.11.3, 4.12.0, 4.12.1, 4.13.0, 4.14.0, 4.15.0, 4.16.0, 4.17.0 ]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main

    - name: mvn install
      run: cd $GITHUB_WORKSPACE/main && mvn install
      
    - name: Checkout client
      uses: actions/checkout@v4
      with:
        repository: SiyaoIsHiding/driver-example-app
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
        ref: github-action
        path: client

    - name: Run client app
      run: |
        cd $GITHUB_WORKSPACE/client 
        sed -i "s|\<driver.version>.*<\/driver.version>|<driver.version>${{ matrix.driver_version }}<\/driver.version>|" pom.xml
        cat pom.xml
        mvn compile exec:java -Dexec.mainClass="org.example.Main"
        
